export enum Constants {
  SET_LOADING = 'FIELD_CUSTOMIZERS_SET_LOADING',
  SET_LISTS = 'FIELD_CUSTOMIZERS_SET_LISTS',
  SET_LISTS_WITH_CUSTOMIZERS = 'FIELD_CUSTOMIZERS_SET_LISTS_WITH_CUSTOMIZERS',
  SET_SELECTED_LIST_ID = 'FIELD_CUSTOMIZERS_SET_SELECTED_LIST_ID',
  SET_ALL_FIELDS_FOR_LIST = 'FIELD_CUSTOMIZERS_SET_ALL_FIELDS_FOR_LIST',
  SET_ERROR = 'FIELD_CUSTOMIZERS_SET_ERROR',
}