export enum Constants {
  SET_LOADING = 'SITE_PROVISIONING_SET_LOADING',
  SET_ERROR = 'SITE_PROVISIONING_SET_ERROR',
  SET_ACTIVE_TAB = 'SITE_PROVISIONING_SET_ACTIVE_TAB',
  SET_SITE_SCRIPTS = 'SITE_PROVISIONING_SET_SITE_SCRIPTS',
  SET_SITE_DESIGNS = 'SITE_PROVISIONING_SET_SITE_DESIGNS',
  SET_SELECTED_SCRIPT = 'SITE_PROVISIONING_SET_SELECTED_SCRIPT',
  SET_SELECTED_DESIGN = 'SITE_PROVISIONING_SET_SELECTED_DESIGN',
}
