export enum Constants {
  SET_LOADING = 'FORM_CUSTOMIZERS_SET_LOADING',
  SET_LISTS = 'FORM_CUSTOMIZERS_SET_LISTS',
  SET_LISTS_WITH_CUSTOMIZERS = 'FORM_CUSTOMIZERS_SET_LISTS_WITH_CUSTOMIZERS',
  SET_SELECTED_LIST_ID = 'FORM_CUSTOMIZERS_SET_SELECTED_LIST_ID',
  SET_ERROR = 'FORM_CUSTOMIZERS_SET_ERROR',
}